# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6a2b5d48005001869ca5c14feaac9941a6194d2499834699d07a588ff6fa3bb40b145694163ac9ef8edaa43ebdcd5da4313ceafb16f5e770dcd28302a6006d1d

test:
  secret_key_base: d581fdc641d1fe9e59d534e0f314cd38e7262c17c71b94290d20106950ecc15ac9e5c56cc09f1aed95c8f7182c45dc5b1ee1981a22b77740ca3df1fb9701b59e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
